run integration tests on chrome

diff --git a/.github/workflows/demo.yaml b/.github/workflows/demo.yaml
--- a/.github/workflows/demo.yaml
+++ b/.github/workflows/demo.yaml
@@ -40,8 +40,8 @@ jobs:
         run: dart format --set-exit-if-changed .
         working-directory: ${{ env.PATH_TO_APP }}
 
-  build_and_test:
-    name: Build & Test Demo App
+  test_and_build:
+    name: "Web: Test Demo App & build on tags"
     needs: lint
     runs-on: ubuntu-latest
     steps:
@@ -64,12 +64,28 @@ jobs:
         run: flutter pub get
         working-directory: ${{ env.PATH_TO_APP }}
 
-      - name: Run tests
-        run: flutter test
-        working-directory: ${{ env.PATH_TO_APP }}
+      - name: Install ChromeDriver
+        uses: browser-actions/setup-chrome@v2
+        with:
+          install-chromedriver: true
+      - name: Verify ChromeDriver install
+        run: chromedriver --version
+
+      - name: Run integration tests (Web)
+        run: |
+          chromedriver --port=4444 &
+          flutter drive --driver=test_driver/integration_test.dart --target=integration_test/demo_test.dart -d chrome --dart-define=CI=true
+          # We have to check the output for failed tests matching the string "[E]"
+          output=$(<output.log)
+          if [[ "$output" =~ \[E\] ]]; then
+          # You will see "All tests passed." in the logs even when tests failed.
+          echo "All tests did not pass. Please check the logs for more information."
+          exit 1
+          fi
+        working-directory: ${{ github.workspace }}
 
       - name: Build app for web
-        if: startsWith(github.ref, 'refs/tags/v') # Only build for deployment on tags
+        # if: startsWith(github.ref, 'refs/tags/v') # Only build for deployment on tags
         run: flutter build web --base-href "${{ steps.pages.outputs.base_path }}/"
         working-directory: ${{ env.PATH_TO_APP }}
 
@@ -81,7 +97,7 @@ jobs:
 
   deploy:
     name: Deploy Demo App to GitHub Pages
-    needs: build_and_test
+    needs: test_and_build
     if: startsWith(github.ref, 'refs/tags/v') # Only deploy on version tags
     runs-on: ubuntu-latest
     permissions:
